# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litescope < Formula
  desc "The database operations layer for AI apps — schema, migrations & fleet health for SQLite/Turso"
  homepage "https://github.com/croc100/Litescope"
  version "0.3.5"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.5/litescope_0.3.5_darwin_amd64.tar.gz"
      sha256 "b5edaf7943e7cd6343cd160ab94d88c50ff68b277b2952459b99ec8187dd58c6"

      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.5/litescope_0.3.5_darwin_arm64.tar.gz"
      sha256 "e981d5c9484a24c055061911e902542a2292d74638e24a71eb05cf5dfe38c892"

      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.5/litescope_0.3.5_linux_amd64.tar.gz"
      sha256 "5616b35c99ee770404f4a04455dd55bb4dc67fd0d2fe7d575c9ebd656776ba2e"
      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.5/litescope_0.3.5_linux_arm64.tar.gz"
      sha256 "77c9d29cd197f07157c518a8f6314d08abc84334e9daaaff11fdf3e453709487"
      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  test do
    system "#{bin}/litescope", "--version"
  end
end
