# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litescope < Formula
  desc "The database operations layer for AI apps — schema, migrations & fleet health for SQLite/Turso"
  homepage "https://github.com/croc100/Litescope"
  version "0.6.3"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croc100/Litescope/releases/download/v0.6.3/litescope_0.6.3_darwin_amd64.tar.gz"
      sha256 "32165373b6d2ac7db1c2d72c76192145c87a73933f1e7e47569a9195c4698411"

      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croc100/Litescope/releases/download/v0.6.3/litescope_0.6.3_darwin_arm64.tar.gz"
      sha256 "aad42e41fcb1f95dc3d122fc28f88c8e057b6a37c43120c3992d1cefbce2b850"

      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/Litescope/releases/download/v0.6.3/litescope_0.6.3_linux_amd64.tar.gz"
      sha256 "6224efa2c8388b23f0c7178e720edc6b31183edcbb3ac203cbb2f3db0e550544"
      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/Litescope/releases/download/v0.6.3/litescope_0.6.3_linux_arm64.tar.gz"
      sha256 "7b3c7e77ec898a089d6968a3b93a2670b9d1c562a1de6d8e1b703821b69f0eaf"
      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  test do
    system "#{bin}/litescope", "--version"
  end
end
