# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litescope < Formula
  desc "The database operations layer for AI apps — schema, migrations & fleet health for SQLite/Turso"
  homepage "https://github.com/croc100/Litescope"
  version "0.3.3"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.3/litescope_0.3.3_darwin_amd64.tar.gz"
      sha256 "fc311926533a32af6f4902a3542e38f8bc33b3d05589b055ff214dc5ea013a8e"

      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.3/litescope_0.3.3_darwin_arm64.tar.gz"
      sha256 "b52ab46dd31375cf82f5e5516f7f851205e62c88826af598f74a88d1149b58dd"

      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.3/litescope_0.3.3_linux_amd64.tar.gz"
      sha256 "c45b7b58567e76396f52e20a3b6f9c01874a8609d0c9eaaf806b0ff3f73d085f"
      define_method(:install) do
        bin.install "litescope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/croc100/litescope-dist/releases/download/v0.3.3/litescope_0.3.3_linux_arm64.tar.gz"
      sha256 "73a9401ed5039b702597a1f6db3c0167dbeed640104b38fa097e38eb4173dba0"
      define_method(:install) do
        bin.install "litescope"
      end
    end
  end

  test do
    system "#{bin}/litescope", "--version"
  end
end
